// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf3CsFPzCUPOWvKuuk9PZ_ELTq_l3LL34',
    appId: '1:243207565890:android:d48dd79b4d1f15b081f3db',
    messagingSenderId: '243207565890',
    projectId: 'auth-a5961',
    databaseURL: 'https://auth-a5961.firebaseio.com',
    storageBucket: 'auth-a5961.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYULtx6AkBKC2jpDojWD4IiIM71bb6EMU',
    appId: '1:243207565890:ios:2d5c687996b2b43181f3db',
    messagingSenderId: '243207565890',
    projectId: 'auth-a5961',
    databaseURL: 'https://auth-a5961.firebaseio.com',
    storageBucket: 'auth-a5961.appspot.com',
    androidClientId:
        '243207565890-0u9k5f60mk39fsg5n8aatr824ce9eg3v.apps.googleusercontent.com',
    iosClientId:
        '243207565890-0j2l74frh7tjrrfkl3o9skjpr6ansdu7.apps.googleusercontent.com',
    iosBundleId: 'com.example.bitInitial',
  );
}
